params:
  seed: 0

  # environment wrapper clipping
  env:
    # read from the env wrapper
    clip_observations: 50.0
    clip_actions: 1.0

  algo:
    name: sac

  model:
    name: soft_actor_critic

  # doesn't have this fine grained control but made it close
  network:
    name: soft_actor_critic
    separate: True
    space:
      continuous:
        mu_activation: None
        sigma_activation: None

        mu_init:
          # name: default
          name: const_initializer
          val: 0
        sigma_init:
          name: const_initializer
          val: 0
        fixed_sigma: True
    mlp:
      units: [512, 256, 128]
      activation: elu
      d2rl: False

      initializer:
        # name: default
        # name: kaiming_normal
        name: orthogonal
      regularizer:
        name: None
      
    log_std_bounds: [-5, 2]

  load_checkpoint: False # flag which sets whether to load the checkpoint
  load_path: '' # path to the checkpoint to load

  config:
    name: manager_sac_rl_games_stepping_stone_mlp_blind
    env_name: rlgpu
    device: 'cuda:0'
    device_name: 'cuda:0'
    multi_gpu: False

    # common parameters
    mixed_precision: True
    normalize_input: True
    normalize_value: True
    num_actors: -1  # configured from the script (based on num_envs)
    reward_shaper:
      scale_value: 1.0
    gamma: 0.99
    entropy_coef: 0.001
    score_to_win: 20000
    # max_epochs: 10000
    max_epochs: 6000
    save_best_after: 500
    save_frequency: 500

    # SAC specific parameters
    num_steps_per_episode: 36
    horizon_length: ${.num_steps_per_episode}
    init_alpha: 1.0 # dual parameter initial value
    alpha_lr: 1e-4 # dual parameter learning rate
    actor_lr: 1e-4 # actor network learning rate
    critic_lr: 1e-4 # critic network learning rate
    critic_tau: 5e-3 # soft update parameter
    learnable_temperature: True
    num_warmup_steps: 0 # total number of warmup steps: num_actors * num_steps_per_episode * num_warmup_steps
    batch_size: 216 # 24 * 36 / 4 = 216
    # batch_size: 576 # 64 * 36 / 4 = 576
    # batch_size: 512
    replay_buffer_size: 1000000
    # bound_loss_type: regularization
    bound_loss_type: bound
    bounds_loss_coef: 0.005
  
  log:
    logger: wandb
    wandb_project_name: rl_mpc_manager_stepping_stone_blind
    wandb_entity: jnskkmr
    name: sac_rl_games_mlp