seed: 42
n_timesteps: !!float 5e8
policy: "MlpPolicy"
n_steps: 24
gamma: 0.99
gae_lambda: 0.95
n_epochs: 5
n_batches: 4
ent_coef: 0.01
sde_sample_freq: 4
max_grad_norm: 1.0
vf_coef: 1.0
learning_rate: lin_3e-4
use_sde: True
clip_range: 0.2
device: "cuda:0"
mixture_coeff: 0.2
target_kl: 0.01
policy_kwargs: "dict(
  ortho_init=True,
  activation_fn=nn.ELU,
  net_arch=[512, 256, 128],
  squash_output=True,
  )"
student_policy_kwargs: "dict(
  ortho_init=True,
  activation_fn=nn.ELU,
  net_arch=[512, 256, 128],
  lstm_hidden_size=128,
  squash_output=True,
  use_sde=True,
  )"