# Reference: https://github.com/DLR-RM/rl-baselines3-zoo/blob/master/hyperparams/sac.yml
# Each configuration, refer to https://stable-baselines3.readthedocs.io/en/master/modules/sac.html#stable_baselines3.sac.SAC
seed: 42
n_timesteps: !!float 5e8
policy: 'MlpPolicy'
learning_rate: !!float 1e-4
buffer_size: 1000000
batch_size: 256
ent_coef: 'auto_0.001'
gamma: 0.98
tau: !!float 5e-3
train_freq: 10
gradient_steps: -1
learning_starts: 0
n_steps: 3
use_sde: True
normalize_input: True
normalize_value: True
policy_kwargs: "dict(
                  log_std_init=-1,
                  activation_fn=nn.ELU,
                  net_arch=[512,256,128], 
                  clip_mean=1.0, 
                )"